apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  ports:
  - port: {{ .Params.SCHEMA_REGISTRY_PORT }}
  selector:
    app: schema-registry
  clusterIP: None
