version: 2.1

jobs:
  test:
    machine:
      enabled: true
    parameters:
      kubernetes_version:
        type: string
    description: "Run KUDO Operators tests against a Kubernetes cluster."
    steps:
      - checkout
      - run: make KUBERNETES_VERSION=<< parameters.kubernetes_version >> test

workflows:
  test-1.17:
    jobs:
      - test:
          kubernetes_version: 1.17.0
  test-1.16:
    jobs:
      - test:
          kubernetes_version: 1.16.0
  test-1.15:
    jobs:
      - test:
          kubernetes_version: 1.15.0
